config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources 'posts', except: [:destroy] do
    member do
      post :vote
    end
    resources 'comments', only: [:create] do
      member do
        post :vote
      end
    end
  end
  resources 'categories', only: [:new, :create, :show]
  resources 'users', only: [:create, :show, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
  validates :name, presence: true, uniqueness: true

  before_save :generate_slug

  def generate_slug
    self.slug = self.name.gsub(" ","-").downcase
  end

  def to_param
    self.slug    
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  has_many :votes, as: :voteable
  validates :body, presence: true

  def total_votes
    self.upvote - self.downvote
  end

  def upvote
    self.votes.where(vote: true).size
  end

  def downvote
    self.votes.where(vote: false).size
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable

  after_validation :generate_slug

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  def total_votes
    upvote - downvote
  end

  def upvote
    self.votes.where(vote: true).size
  end

  def downvote
    self.votes.where(vote: false).size
  end

  def generate_slug
    self.slug = self.title.gsub(' ','-').downcase
  end

  def to_param
    self.slug
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  has_secure_password validations: false
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 3}

  before_save :generate_slug

  def generate_slug
    self.slug = self.username.gsub(" ", "-").downcase
  end

  def to_param
    self.slug
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true
  validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Login First!!"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user ,only: [:new, :create]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "You have created a category!!"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find_by(slug: params[:id])
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user
    if @comment.save
      flash[:notice] = "You create a Comment Successfully!!"
      redirect_to post_path(@post)
    else
      render '/posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.errors.any?
          flash[:error] = "You can only vote to a comment once!!"
        else
          flash[:notice] = "Your vote has been counted!!"
        end
        redirect_to :back
      end
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user    ##Todo Change if we have the authentication on users
    if @post.save
      flash[:notice] = "You Create a Post Successfully!"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'You updated Successfully!!'
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def vote
    @vote = Vote.create(vote: params[:vote], voteable: @post, creator: current_user)
    respond_to do |format|
      format.html do
        if @vote.errors.any?
          flash[:error] = "You can only vote to a post once!!"
        else
          flash[:notice] = "Your count has been counted!!"
        end
        redirect_to :back
      end
      format.js
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      flash[:notice] = "login sueccessfully!!"
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Have some errors in your username or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logout sueccessfully!!'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :requrie_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_param)
    if @user.save
      flash[:notice] = "Registration Success!!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_param)
      flash[:notice] = "Update Profile Successfully!!"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show
  end

  private

  def user_param
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def requrie_same_user
    if @user != current_user
      flash[:error] = "You can't do this"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.start_with?("http://") ? str : "http://#{str}"
  end

  def display_datetime(datetime)
    datetime.strftime("%d/%m/%Y %H:%M %P")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a new category' %>
<%= render 'shared/errors', object: @category %>
<div class="well">
  <%= form_for @category do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to("All Posts", posts_path) + " &raquo #{@category.name}".html_safe %>
 
<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<% show_which_post ||= false %>
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
      <br>
    <% end %>
    <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %></span>
    votes
    <br>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="well span8">
    <em>"<%= comment.body %>"</em>
    <% if show_which_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <p>
      <span class="quiet"> by </span> <%= link_to comment.creator.username, user_path(comment.creator) %>
      <small>create at <%= display_datetime(comment.created_at) %></small>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $('#comment_<%= @comment.id %>_votes').html(<%= @comment.total_votes %>);
<% else %>
  alert("You can only vote once!!");
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'Link' %>
  </li>
</ul>

<div class="nav_item">
  <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
</div>

<div class="dropdown nav_item">
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories
    <span class="caret"></span>
  <% end %>
  <ul class="dropdown-menu" role="menu">
    <% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
    <li class="divider"></li>
    <li>
      <%= link_to new_category_path  do %>
        <i class="icon-plus"></i>
        New Category
      <% end %>
    </li>
  </ul>
</div>

<% if !logged_in? %>
  <div class="nav_item">
    <%= link_to 'Register', register_path, class: 'btn btn-success btn-small' %>
  </div>
  <div class="nav_item">
    <%= link_to 'Log in', login_path, class: 'btn btn-default btn-small' %>
  </div>
<% else %>
  <div class="dropdown nav_item">
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
      <%= current_user.username %>
      <span class="caret"></span>
    <% end %>
  <ul class="dropdown-menu" role="menu">
    <li>
      <%= link_to user_path(current_user) do %>
        <i class="icon-user"></i>
        Show profile
      <% end %>
    </li>
    <li>
      <%= link_to edit_user_path(current_user) do %>
        <i class="icon-pencil"></i>
        Edit profile
      <% end %>
    </li>
    <li>
      <%= link_to logout_path do %>
        <i class="icon-circle-arrow-left"></i>
        Log out
      <% end %>
    </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', object: @post %>
<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
      <%  b.label(class: 'checkbox inline') { b.check_box(class: 'checkbox') + b.text } %>
    <% end %>
    <hr>
   <br>
    <%= f.submit class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
      <br>      
    <% end %>
    <span id="post_<%= post.slug %>_votes"><%= post.total_votes %></span>
    votes
    <% if logged_in? %>
      <br>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quiet"> post_by </span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small>create at <%= display_datetime(post.created_at) %></small>
    </p>
    <span> <%= link_to "#{post.comments.size} comments", post_path(post) %> </span>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this Post' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<% if current_user %>
  <h5>Hi, Welcome to Postit <%= current_user.username %></h5>
<% end %>
<%= render 'shared/content_title', title: 'All Posts' %>
<%= render @posts %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'New Post' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class="pull-right">
    [<%= link_to 'Edit this Post', edit_post_path(@post) %>]
  </p>  
<% end %>


<p>
  <%= render @post.categories %>
</p>
<%= render 'shared/content_title', title: @post.title %>
<%= @post.description %>
<hr>

<% if logged_in? %>
  <div class="row">
    <div class="span8">
      <%= render 'shared/errors', object: @comment %>
      <%= form_for [@post, @comment] do |f| %>
        <div class="controll-group">
          <%= f.label :body, 'Leave a Comment' %> 
          <%= f.text_area :body, rows: 5 %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %> 
    </div>
  </div>
<% end %>

<h5>Comments</h5>
<% @post.comments.reload.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%= @post.slug %>_votes').html(<%= @post.total_votes %>);
<% else %>
  alert("You can only vote once!!");
<% end %>

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title %>
  <hr>
</p>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <h5>Please fix these errors</h5>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>
<div class="well">
  <%= form_for @user do |f| %>
    <div class="control-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class="control-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <%= f.submit @user.new_record? ? "Register" : "Update", class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Profile' %>
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Registration' %>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile : #{@user.username}" %>
<div class="well">
  <h5>Username : <%= @user.username %></h5>
</div>

<h3><%= @user.username %>'s activities</h3>
<div class="nav nav-tabs">
  <li class="<%= 'active' if params[:tab].nil? %>">
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class="<%= 'active' if params[:tab] == 'comment' %>">
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comment') %>
  </li>

</div>

<% if params[:tab].nil? %>
  <% @user.posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
<% elsif params[:tab] == 'comment' %>
  <% @user.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment, show_which_post: true %>
  <% end %>
<% end %>